version: "3.8"

services:
  flow-auto-front:
    build:
      context: ./frontend
      args:
        - VITE_SERVER_URL=http://localhost:5001 
    container_name: flow-auto-front
    ports:
      - "80:80"
    networks:
      - flow-auto-net
    depends_on:
      - flow-auto-backend
    restart: unless-stopped

  flow-auto-backend:
    build:
      context: ./server
    container_name: flow-auto-backend
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env 
    environment:
      - NODE_ENV=production
    networks:
      - flow-auto-net
    restart: unless-stopped

networks:
  flow-auto-net: