apiVersion: v1
kind: Secret
metadata:
  name: flow-auto-backend-secret
  namespace: flow-auto-ns
type: Opaque
data:

  PORT: <YOUR_BASE64_PORT>
  MONGODB_URL: <YOUR_BASE64_ENCODED_MONGO_URI>
  JWT_SECRET_KEY: <YOUR_BASE64_ENCODED_JWT_SECRET>
  VITE_SERVER_URL: <YOUR_BASE64_ENCODED_URL>
  GOOGLE_CLIENT_ID: <YOUR_BASE64_ENCODED_GOOGLE_CLIENT_ID>
  GOOGLE_CLIENT_SECRET: <YOUR_BASE64_ENCODED_GOOGLE_CLIENT_SECRET>
  NOTION_CLIENT_ID: <YOUR_BASE64_ENCODED_NOTION_CLIENT_ID>
  NOTION_CLIENT_SECRET: <YOUR_BASE64_ENCODED_NOTION_CLIENT_SECRET>
  DISCORD_CLIENT_ID : <YOUR_BASE64_ENCODED_DISCORD_CLIENT_ID>
  DISCORD_CLIENT_SECRET: <YOUR_BASE64_ENCODED_DISCORD_CLIENT_SECRET>
  DISCORD_BOT_TOKEN: <YOUR_BASE64_ENCODED_DISCORD_BOT_TOKEN>
  GEMINI_API_KEY: <YOUR_BASE64_ENCODED_GEMINI_API_KEY>