apiVersion: v1
kind: Service
metadata:
  name: flow-auto-frontend-svc
  namespace: flow-auto-ns
spec:
  selector:
    app: flow-auto-frontend-pod-classify
  ports:
    - protocol: TCP
      port: 80          
      targetPort: 80    
  type: ClusterIP


apiVersion: v1
kind: Service
metadata:
  name: flow-auto-backend-svc
  namespace: flow-auto-ns
spec:
  type: ClusterIP
  selector:
    app: flow-auto-backend-pod-classify
  ports:
    - protocol: TCP
      port: 5001          
      targetPort: 5001